version: '2.1'

services:
  super-bot-whatsapp:
    image: super-bot-whatsapp
    build: .
    environment:
      NODE_ENV: development
      SUPERBOT_URL: http://host.docker.internal:3000/message
      CALLBACK_HOST: localhost
      PUPPETEER_MODE: headless
    ports:
      - 3001:3001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 .